spring:
  application:
    name: appointment-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/ecommerce-store}
    username: ${DB_USER:username}
    password: ${DB_PASSWORD:password}
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 9090
